-- Cloud Infrastructure Tables

-- Cloud provider configurations
CREATE TABLE IF NOT EXISTS cloud_configs (
    id SERIAL PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    provider VARCHAR(20) NOT NULL CHECK (provider IN ('aws', 'gcp', 'azure')),
    name VARCHAR(255) NOT NULL,
    region VARCHAR(50) NOT NULL,
    -- AWS credentials
    access_key_id TEXT,
    secret_access_key TEXT,
    -- GCP credentials
    service_account_key TEXT,
    project_id VARCHAR(255),
    -- Azure credentials
    client_id TEXT,
    client_secret TEXT,
    tenant_id TEXT,
    subscription_id TEXT,
    is_default BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_cloud_configs_user ON cloud_configs(user_id);

-- Infrastructure plans generated by AI
CREATE TABLE IF NOT EXISTS infrastructure_plans (
    id VARCHAR(36) PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    config_id INTEGER NOT NULL REFERENCES cloud_configs(id) ON DELETE CASCADE,
    prompt TEXT NOT NULL,
    summary TEXT,
    resources JSONB,
    estimated_cost VARCHAR(50),
    terraform_code TEXT NOT NULL,
    status VARCHAR(20) DEFAULT 'draft' CHECK (status IN ('draft', 'deploying', 'deployed', 'failed', 'destroyed')),
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_infrastructure_plans_user ON infrastructure_plans(user_id);
CREATE INDEX idx_infrastructure_plans_config ON infrastructure_plans(config_id);

-- Deployment tracking
CREATE TABLE IF NOT EXISTS deployments (
    id VARCHAR(36) PRIMARY KEY,
    plan_id VARCHAR(36) NOT NULL REFERENCES infrastructure_plans(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    status VARCHAR(20) DEFAULT 'initializing' CHECK (status IN ('initializing', 'planning', 'applying', 'completed', 'failed')),
    logs JSONB DEFAULT '[]',
    outputs JSONB DEFAULT '{}',
    error TEXT,
    created_at TIMESTAMP DEFAULT NOW(),
    completed_at TIMESTAMP
);

CREATE INDEX idx_deployments_plan ON deployments(plan_id);
CREATE INDEX idx_deployments_user ON deployments(user_id);
